# Generated by Django 2.2.13 on 2020-06-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200607_0831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
